version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/mnt/workspace
    working_dir: /mnt/workspace
    ports:
      - 8080:8080
    tty: true
